### ISSUE TITLE
Problem ORS tool 

### ISSUE THREAD

**Issue by PeterClaro** [GIScience/orstools-qgis-plugin#245]
When I use the Isochrones from layer tool. I get an error, which should not be there following the instructions on the website. Does anyone know what could be done?

#### Here's what I did

---
#### Here's what I got

Traceback (most recent call last):
File "/Users/petereisma/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/isochrones_layer_proc.py", line 189, in processAlgorithm
response = ors_client.request("/v2/isochrones/" + profile, {}, post_json=params)
File "/Users/petereisma/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/client.py", line 195, in request
return json.loads(content.decode("utf-8"))
File "/Applications/QGIS 2.app/Contents/MacOS/../Resources/python/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/Applications/QGIS 2.app/Contents/MacOS/../Resources/python/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/Applications/QGIS 2.app/Contents/MacOS/../Resources/python/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

---
#### Here's what I was expecting

---

**Comment by koebi** [comment]
Hey,
could you describe what you did, ideally providing a minimum viable input layer and the corresponding parameters that exhibit the bug?

It's rather hard to debug these issues without any information on what the input was.
