### ISSUE TITLE
Version 1.8.0 will not load because of python version mismatch

### ISSUE THREAD

**Issue by archiboi69** [GIScience/orstools-qgis-plugin#258]
#### Here's what I did
I upgraded the plugin to version 1.8.0 and on reload it throws an exception. Quick search showed it may be a python version problem - Qgis python is 3.9.5 and match function is from python 3.10

Couldn't load plugin 'ORStools' due to an error when calling its classFactory() method 
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/__init__.py", line 43, in classFactory
    from .ORStoolsPlugin import ORStools
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/ORStoolsPlugin.py", line 35, in 
    from .gui import ORStoolsDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/gui/ORStoolsDialog.py", line 73, in 
    from ORStools.common import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/directions_core.py", line 36, in 
    from ORStools.utils import convert, logger
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/utils/convert.py", line 142
    match extra_info:
          ^
SyntaxError: invalid syntax
 Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)]  QGIS version: 3.36.1-Maidenhead Maidenhead, 3e589453264

**Comment by archiboi69** [comment]
Version 1.8.1 fixed the previous exception, but there is a new one:

Couldn't load plugin 'ORStools' due to an error when calling its classFactory() method 

TypeError: unsupported operand type(s) for |: 'type' and 'type' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/__init__.py", line 43, in classFactory
    from .ORStoolsPlugin import ORStools
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/ORStoolsPlugin.py", line 35, in 
    from .gui import ORStoolsDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/gui/ORStoolsDialog.py", line 73, in 
    from ORStools.common import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/directions_core.py", line 36, in 
    from ORStools.utils import convert, logger
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users//Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/utils/convert.py", line 92, in 
    def decode_extrainfo(extra_info: str, key: int) -> str | int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.36.2-Maidenhead Maidenhead, 6d250527200

**Comment by merydian** [comment]
Hi, 

thanks for posting about this. Its fixed now an you should be able to simply update via the Plugin Manager.

Best regards

**Comment by archiboi69** [comment]
Thank you works now!
