### ISSUE TITLE
Cannot install ORS Tools 

### ISSUE THREAD

**Issue by anitagraser** [GIScience/orstools-qgis-plugin#271]
When trying to install the plugin in a non-default user profile, I get the following error: 

```
Konnte Erweiterung 'ORStools' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

TypeError: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "C:\Users/GraserA/AppData/Local/miniconda3/envs/qgis/Library/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/GraserA/AppData/Roaming/QGIS/QGIS3\profiles\DE/python/plugins\ORStools\__init__.py", line 45, in classFactory
    return ORStools(iface)
  File "C:\Users/GraserA/AppData/Roaming/QGIS/QGIS3\profiles\DE/python/plugins\ORStools\ORStoolsPlugin.py", line 59, in __init__
    locale = QgsSettings().value("locale/userLocale")[0:2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by merydian** [comment]
Hi, thanks for your input. We merged a fix -- as seen above -- that should resolve the issue with the next release.
